---

- name: 'Run playbook-all_nodes-set_hostname.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-set_hostname.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

- name: 'Run 10_SLES_register.yml'
  ansible.builtin.import_playbook: 10_SLES_register.yml

- name: 'Run playbook-all_nodes-zypper_ref_accept_keys.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-zypper_ref_accept_keys.yml

- name: 'Run playbook-all_nodes-install_git.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_git.yml
