---
- name: 'Install git (aka git-core)'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.install_one_or_more_packages'
      vars:
        packages_to_be_installed:
          - git-core
